Common data structures used in Python and R

**Python**
- Primitive Data Structures
    - Integer
    - Float
    - String
    - Boolean
- Non-Primitive Data Structures
    - List & Tuple
    - Dictionary
    - Set
    - File
- [Numpy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html)
    - int32, int64
    - float32, float64
    - array
- Pandas
    - Series
    - DataFrame
    
**R**
- Vector
    - atomic vector
    - list
    - factor
- Matrix
- List
- Data.Frame
- Tibble (a more general data frame)

In [1]:
import numpy as np

%load_ext rpy2.ipython

Question: Create a sequence of integers

In [2]:
%%R
# Atomic Vector
x <- c(1,2,3)
y <- 1:3
z <- seq(from=1, to=3, by=1)

print(x)
print(y)
print(z)

[1] 1 2 3
[1] 1 2 3
[1] 1 2 3


In [3]:
##### Python #####
x1 = [1,2,3]
x2 = list(range(3))
y1 = np.r_[1, 2, 3]
y2 = np.array([1, 2, 3])
z  = np.arange(1, 3+1, 1)

print(x1)
print(x2)
print(y1)
print(y2)
print(z)

[1, 2, 3]
[0, 1, 2]
[1 2 3]
[1 2 3]
[1 2 3]


Question: Create an 3 by 3 identical matrix

In [5]:
%%R
eye3 <- matrix(c(1,0,0,0,1,0,0,0,1), nrow=3, ncol=3)
print(eye3)

print("====================")

eye3 <- diag(c(1, 1, 1))
print(eye3)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1
[1] "===================="
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


In [6]:
##### Python #####
eye3 = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3) # or .reshape(3,-1)
print(eye3)

print("==================")

eye3 = np.diag([1,1,1])
print(eye3)

print("==================")

eye3 = np.eye(3, dtype=np.int)
print(eye3) 

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
