Here I compare the subsetting of Numpy and Base r

In [4]:
import numpy as np
import numpy.random as rand

%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


# subset of vector

First generate 20 numbers from standard normal distribution

In [5]:
%%R
x <- rnorm(10)
print(x)

 [1] -1.45657316  0.70912795  0.14633641 -0.96819842  0.07366553 -0.23428949
 [7] -0.38753825  0.11847186 -0.08541179 -0.67781977


In [8]:
##### Python #####
x = rand.normal(size=10)
print(x)

[-0.24265364  1.16924064  0.37838154 -0.87883634 -0.7856068  -1.02531119
  0.1786645   1.127267    0.55828736 -1.79406442]


simple subsetting

In [11]:
%%R
print(x[2:4])
print(x[seq(from = 1, to = length(x), by = 3)])
print(x[x < 0])
print(x[which(x < 0)])

[1]  0.7091279  0.1463364 -0.9681984
[1] -1.4565732 -0.9681984 -0.3875382 -0.6778198
[1] -1.45657316 -0.96819842 -0.23428949 -0.38753825 -0.08541179 -0.67781977
[1] -1.45657316 -0.96819842 -0.23428949 -0.38753825 -0.08541179 -0.67781977


In [12]:
##### Python #####
print(x[1:5])
print(x[1::3])
print(x[x<0])
print(x[np.where(x<0)])

[ 1.16924064  0.37838154 -0.87883634 -0.7856068 ]
[ 1.16924064 -0.7856068   1.127267  ]
[-0.24265364 -0.87883634 -0.7856068  -1.02531119 -1.79406442]
[-0.24265364 -0.87883634 -0.7856068  -1.02531119 -1.79406442]


# subset of matrix

First, create a 4 by 6 matrix

In [14]:
%%R
mat <- matrix(rnorm(4*6), nrow=4, ncol=6)
#mat <- matrix(rnorm(4*6), nrow=4)
print(mat)

           [,1]       [,2]       [,3]        [,4]       [,5]       [,6]
[1,] -0.1838415 -1.5361920 -0.9835689 -0.01015682  0.1220143 -0.7991400
[2,] -0.4933036 -0.7881019  0.7529150 -0.51367463  0.9793835  1.1461285
[3,]  1.4407869  0.9021991 -1.2138188 -0.02656989  0.9683008  1.8976368
[4,]  0.4200226  0.6918381 -1.1158480  1.14928642 -1.1670505 -0.6647891


In [15]:
##### Python #####
mat = np.array(np.random.normal(size=4*6)).reshape(4,6)
#mat = np.array(np.random.normal(size=4*6)).reshape(4,-1)
print(mat)

[[ 0.8913369   0.43987957  2.15679201 -1.00972589 -0.40415706  0.14154288]
 [-0.34936218  0.04113661  0.73440866  0.16278888 -0.6176729   0.27546497]
 [ 1.05656669 -1.1212385  -1.03610212 -0.43033346 -0.16630389  0.79120501]
 [ 0.16405219  0.33430046 -0.34700156  0.85263504  0.49395786 -0.93621751]]


In [19]:
%%R
cat("The orignal matrix\n")
print(mat)
cat("\n===============\n")
cat("The first row\n")
print(mat[1,])
cat("\n===============\n")
cat("The first row (Drop=False)\n")
print(mat[1,,drop=FALSE])
cat("\n===============\n")
cat("The first column\n")
print(mat[,1])
cat("\n===============\n")
cat("The first column (Drop=False)\n")
print(mat[,1,drop=FALSE])

The orignal matrix
           [,1]       [,2]       [,3]        [,4]       [,5]       [,6]
[1,] -0.1838415 -1.5361920 -0.9835689 -0.01015682  0.1220143 -0.7991400
[2,] -0.4933036 -0.7881019  0.7529150 -0.51367463  0.9793835  1.1461285
[3,]  1.4407869  0.9021991 -1.2138188 -0.02656989  0.9683008  1.8976368
[4,]  0.4200226  0.6918381 -1.1158480  1.14928642 -1.1670505 -0.6647891

The first row
[1] -0.18384151 -1.53619205 -0.98356891 -0.01015682  0.12201432 -0.79913998

The first row (Drop=False)
           [,1]      [,2]       [,3]        [,4]      [,5]     [,6]
[1,] -0.1838415 -1.536192 -0.9835689 -0.01015682 0.1220143 -0.79914

The first column
[1] -0.1838415 -0.4933036  1.4407869  0.4200226

The first column (Drop=False)
           [,1]
[1,] -0.1838415
[2,] -0.4933036
[3,]  1.4407869
[4,]  0.4200226


In [23]:
##### Python #####
print("The orignal matrix")
print(mat)
print("\n===============")
print("The first row")
print(mat[1,:])
print("\n===============")
print("The first row (Drop=False)")
print(mat[0,:].reshape(1,-1))
print("\n===============")
print("The first column")
print(mat[:,1])
print("\n===============")
print("The first column (Drop=False)")
print(mat[:,0].reshape(-1,1))

The orignal matrix
[[ 0.8913369   0.43987957  2.15679201 -1.00972589 -0.40415706  0.14154288]
 [-0.34936218  0.04113661  0.73440866  0.16278888 -0.6176729   0.27546497]
 [ 1.05656669 -1.1212385  -1.03610212 -0.43033346 -0.16630389  0.79120501]
 [ 0.16405219  0.33430046 -0.34700156  0.85263504  0.49395786 -0.93621751]]

The first row
[-0.34936218  0.04113661  0.73440866  0.16278888 -0.6176729   0.27546497]

The first row (Drop=False)
[[ 0.8913369   0.43987957  2.15679201 -1.00972589 -0.40415706  0.14154288]]

The first column
[ 0.43987957  0.04113661 -1.1212385   0.33430046]

The first column (Drop=False)
[[ 0.8913369 ]
 [-0.34936218]
 [ 1.05656669]
 [ 0.16405219]]
